- name: Download the GRPC patch if possible
  ansible.builtin.get_url:
    url: "{{ grpc_patch_url }}"
    dest: "/tmp"
    mode: '0644'
  register: download_result
  ignore_errors: true
  tags:
    - install
    - pip
    - grpc

- name: Install grpc patch if available
  ansible.builtin.shell:
    chdir: "/tmp"
    cmd: ". {{ attackmate_dest }}/venv/bin/activate && pip install current"
  when: download_result.status_code | default(404) == 200
  tags:
    - install
    - pip
    - grpc

- name: Grpc patch INFO
  ansible.builtin.debug:
    msg:
    - "No grpc patch available falling back to compile locally"
    - "This will take a while depending on your system"
  when: download_result.status_code | default(403) != 200

- name: Git checkout grpc
  ansible.builtin.git:
    repo: "https://github.com/grpc/grpc"
    dest: "{{ attackmate_grpc_dest }}"
    version: "master"
  when: download_result.status_code | default(403) != 200
  tags:
    - install
    - git
    - grpc

- name: Install packages for sliverfix
  become: true
  ansible.builtin.package:
    name: "{{ attackmate_dev_packages }}"
  tags:
    - install
    - dependencies
  when: download_result.status_code | default(404) != 200

- name: Install grpc requirements
  ansible.builtin.pip:
    requirements: "requirements.txt"
    chdir: "{{ attackmate_grpc_dest }}"
    virtualenv: "{{ attackmate_dest }}/venv"
  tags:
    - install
    - pip
    - grpc
  when: download_result.status_code | default(404) != 200

- name: Uninstall protobuf
  ansible.builtin.pip:
    name: protobuf
    chdir: "{{ attackmate_grpc_dest }}"
    virtualenv: "{{ attackmate_dest }}/venv"
    extra_args: "--yes"
    state: absent
  tags:
    - install
    - pip
    - grpc
  when: download_result.status_code | default(404) != 200

- name: Uninstall grpcio-tools
  ansible.builtin.pip:
    name: grpcio-tools
    chdir: "{{ attackmate_grpc_dest }}"
    virtualenv: "{{ attackmate_dest }}/venv"
    extra_args: "--yes"
    state: absent
  tags:
    - install
    - pip
    - grpc
  when: download_result.status_code | default(404) != 200

- name: Compile grpc
  ansible.builtin.shell:
    chdir: "{{ attackmate_grpc_dest }}"
    cmd: ". {{ attackmate_dest }}/venv/bin/activate && GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True pip install --use-pep517 --no-input ."
  tags:
    - install
    - pip
    - grpc
  when: download_result.status_code | default(404) != 200

- name: Install protobuf
  ansible.builtin.pip:
    name: protobuf
    chdir: "{{ attackmate_grpc_dest }}"
    virtualenv: "{{ attackmate_dest }}/venv"
  tags:
    - install
    - pip
    - grpc

- name: Remove grpc dev-files
  ansible.builtin.shell:
    cmd: "test -d {{ attackmate_grpc_dest }} && rm -rf {{ attackmate_grpc_dest }}"
  tags:
    - install
    - pip
    - grpc
  when: download_result.status_code | default(404) != 200

- name: Lock sliverfix
  ansible.builtin.shell:
    cmd: "touch {{ attackmate_dest }}/venv/.sliverfix"
  tags:
    - install
    - pip
    - grpc
